from django.views.generic import TemplateView
from django.core.mail import send_mail ,EmailMultiAlternatives
from django.shortcuts import render
from django.conf import settings

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart






def contactus(request):
    if request.method == 'POST':
        name = request.POST['fname']
        toemail = request.POST['emailid']
        mycontact = request.POST['contact']
        message = request.POST['mycomment']

        subject="this is auto generated mail do not reply to this mail"
        from_email=settings.EMAIL_HOST_USER

        msg=f"<h3 >Please find below details of {name}</h3>" \
            f"<hr>"\
            f"<h3><b> Name </b>: { name} </h3>" \
            f"<hr>" \
            f"<h3><b>Email_id</b>: { toemail} </h3>" \
            f"<hr>" \
            f"<h3><b>Contact_No</b>: { mycontact} </h3>" \
            f"<hr>" \
            f"<h3><b>Message</b>: { message} </h3>"\
            f"<hr>" \

        to='krishna260692@gmail.com'
        msg = EmailMultiAlternatives(subject, msg, from_email, [to])
        msg.content_subtype='html'
        msg.send()

        send_mail(
            "autogenerated mail do not reply",
            'your message has been successfully sent, we will contact you soon',
            from_email,
            [toemail],
            fail_silently=False,)
        return render(request, 'success.html')
    return render(request, 'contactus.html')



def homecontact(request):
    if request.method == 'POST':
        fname = request.POST['fname']
        lname = request.POST['lname']
        mycontact = request.POST['mycontact']
        toemail = request.POST['mymail']
        message = request.POST['comment']
        subject = "this is auto generated mail do not reply to this mail"
        from_email = settings.EMAIL_HOST_USER

        msg = f"<h3>Please find below details of {fname}</h3>" \
              f"<hr>" \
              f"<h3><b> Name </b>: {fname} </h3>" \
              f"<hr>" \
              f"<h3><b> Name </b>: {lname} </h3>" \
              f"<hr>" \
              f"<h3><b>Contact_no</b>: {mycontact} </h3>" \
              f"<hr>" \
              f"<h3><b>E-mail</b>: {toemail} </h3>" \
              f"<hr>" \
              f"<h3><b>Message</b>: {message} </h3>"\
              f"<hr>" \

        to = 'krishna260692@gmail.com'
        msg = EmailMultiAlternatives(subject, msg, from_email, [to])
        msg.content_subtype = 'html'
        msg.send()

        send_mail(
            "autogenerated mail do not reply",
            'your message has been successfully sent, we will contact you soon',
            from_email,
            [toemail],
            fail_silently=False,
        )
        return render(request, 'success.html')



class about(TemplateView):
    template_name = "about.html"



class phphome(TemplateView):
    template_name = "php.html"



# def newhome(request):

    # email = "krishna260692@gmail.com"
    # subject = "this is new try"
    # content = "is this working"
    #
    # port = 465
    # smtp_server_domain_name = "smtp.gmail.com"
    # sender_mail = "shyamkumar260692@gmail.com"
    # password = "7979747428"
    #
    # ssl_context = ssl.create_default_context()
    # service = smtplib.SMTP_SSL(smtp_server_domain_name, port, context=ssl_context)
    # service.login(sender_mail, password)
    #
    #
    # service.sendmail(sender_mail, email, f"Subject: {subject}\n{content}")
    #
    # service.quit()

def newhome(request):
    if request.method == 'POST':
        name = request.POST['fname']
        tomail= request.POST['emailid']
        mycontact = request.POST['contact']


        login_id = "shyamkumar260692@gmail.com"
        password = "7488812379"

        # tomail = "krishna260692@gmail.com"

        server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
        server.login(login_id, password)

        subject = "new mail"

        message = MIMEMultipart()
        message["From"] = login_id
        message["To"] = tomail
        message["Subject"] = subject

        html = """\
    
        <div style=" text-align: left; "> 
        <table style="padding:10px; border: 1px solid #dddddd;border-color:black;">
          <tr>
            <th>Please find below details:-</th>
    
          </tr>
          <tr style="background-color: gray;">
            <td>Name:-</td>
            <td>krishna kumar  </td>
    
          </tr>
          <tr style="background-color:lightgray ;">
            <td>Contact_No:-</td>
            <td>7979797979</td>
    
          </tr>
          <tr style="background-color:Tomato;">
            <td>Email_Id:-</td>
            <td>krishna260692@gmail.com</td>
    
          </tr>
          <tr style="background-color:lightgray ;">
            <td>Message:- </td>
            <td>hello krishna</td>
    
          </tr>
    
        </table>
        </div>
        """

        part = MIMEText(html, "html")
        message.attach(part)
        server.sendmail(login_id, "krishna260692@gmail.com", message.as_string())
        server.quit()
        return render(request, 'success.html')



















